name: Build and Deploy to Staging

on:
  release:
    types: [published]
    paths:
      - "special-folder/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo HTML
        run: |-
          echo special-folder/text.txt
